name: Benchmark on GPU Server

on:
  workflow_dispatch:

jobs:
  release-windows:
    runs-on: [self-hosted, windows, x64, gpu]
    name: Benchmark on self-hosted GPU runner
    steps:
      #checkout code
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4
  
      # Not needed, already set in path
      #Locate MSBuild.exe and add to PATH
      # - name: Add MSBuild to PATH
      #   id: setup_msbuild
      #   uses: microsoft/setup-msbuild@v2
      #   with:
      #     msbuild-architecture: x64
         
      #Run MSBuild Release
      - name: Run MSBuild Release
        id: run_msbuild_release
        working-directory: .\
        run: msbuild.exe .\ -t:VulOptiSim -property:Configuration=Release -property:Platform=x64
  
      #Copy the assest folders into the release folder
      - name: Copy assets to x64/Release
        id: copy_assets
        shell: cmd
        run: |
          mkdir x64\
          xcopy /E /I /Y models x64\models
          xcopy /E /I /Y shaders x64\shaders
          xcopy /E /I /Y textures x64\textures

      #Run project
      - name: Run project
        id: run_project
        working-directory: x64\Release
        shell: cmd
        run: VulOptiSim.exe


      #See: https://ss64.com/nt/for.html
      - name: Check Score
        id: check_score
        shell: cmd
        working-directory: x64\Release
        run: |
          set REPO_NAME=%GITHUB_REPOSITORY%
          for /F "tokens=2 delims=/" %%A in ("%REPO_NAME%") do set TEAM_NAME=%%A
          ScoreMonitor.exe performance_log.txt %TEAM_NAME%